### ISSUE TITLE
Ignoring Strand Switch Angles

### ISSUE THREAD

**Issue by DNAcer** [NATuG3/NATuG3#16]
In points x_coord_from_angle it calculates the interior angle as 
     theta_interior: float = domain.theta_m
which ignores any contribution to the interior angle associated with a strand switch.

In general, the interior angle should be 
interior_angle=m*theta_c - s*theta_s
or, equivalently 
interior_angle= m*theta_c - s*g
these two equations can take on all the same values, however, to generate the same value for the interior angle, you will need to use a different value of m in the two equations.

**Comment by 404Wolf** [comment]
Fixed!
