### ISSUE TITLE
Sequence Typeface Optimization

### ISSUE THREAD

**Issue by DNAcer** [NATuG3/NATuG3#18]
It can be difficult to distinguish between C and G when they have a dark line going through them, particularly when they are small. Can we change the font on the sequence printout, particularly in the sideview panel, to use a better, monospaced font? I Think Century might be the best choice, since G and C are quite distinct in that font: 
<img width="230" alt="Screen Shot 2023-03-06 at 1 41 14 AM" src="https://user-images.githubusercontent.com/118033291/223037341-f942764c-0d0b-4c9f-af3d-629b36b6e76d.png">

**Comment by 404Wolf** [comment]
I've just tested this with Courier and Century, and put screenshots of both below. Just let me know which looks better and I'll make the change.

Courier
![image](https://user-images.githubusercontent.com/108041238/223231135-56d4a62f-92e1-408d-90d2-178034f10a66.png)

Century:
![image](https://user-images.githubusercontent.com/108041238/223231454-09fedc63-c55d-42b0-a7e6-5f6e7bc444ca.png)

**Comment by DNAcer** [comment]
Red lines are much more my concern than the thinner black and gray ones.
<img width="490" alt="Screen Shot 2023-03-06 at 10 59 37 PM" src="https://user-images.githubusercontent.com/118033291/223317445-151db656-ffd5-4d62-8d58-f1072f61730a.png">

**Comment by DNAcer** [comment]
Can we put a semi-transparent white background box on each letter?
