### ISSUE TITLE
Nucleoside Information Not Visible

### ISSUE THREAD

**Issue by DNAcer** [NATuG3/NATuG3#39]
Nucleoside information is not visible in small text boxes.

<img width="472" alt="Screen Shot 2023-05-21 at 11 05 21 PM" src="https://github.com/NATuG3/NATuG3/assets/118033291/52bb5e62-d450-4dd5-840e-4447354ed53d">

**Comment by 404Wolf** [comment]
Resolved.

![image](https://github.com/NATuG3/NATuG3/assets/108041238/d4df95b4-60e0-4381-903b-1e13d7b8067b)
