### ISSUE TITLE
One less Dot in Top View for Unclosed Structures

### ISSUE THREAD

**Issue by DNAcer** [NATuG3/NATuG3#55]
There should not be a dot between domain N and 1 in the top view plot unless the tube is actually closed properly (i.e. the domains are the proper distance apart, and the line segments that are supposed to meet up are aligned with each other and facing the point of contact between the domains.)
<img width="394" alt="ExtraDot" src="https://github.com/NATuG3/NATuG3/assets/118033291/67ed2f7d-5bb2-482a-ad42-56e6b2ce90bf">

**Comment by 404Wolf** [comment]
Solved by adding to the top view button addition loop:

```py
if (not domains_closed) and (index == len(u_coords) - 1):
    break
```
