### ISSUE TITLE
Saving Junctions etc! Also - warn about losing work!

### ISSUE THREAD

**Issue by DNAcer** [NATuG3/NATuG3#56]
We absolutely need to have a visible button to save the entire structure. Frankly, being able to save parts of the structure independently is almost a bug. Someone who has entered in a bunch of angles into the domains panel, and then made a bunch of junctions, when they click the save icon, wants to save the junctions as well as the angles. If they quit without saving, a dialog box should arise telling them that they are going to lose work.

1) Put prominent buttons labelled "Save All" and "Load All" on the top bar near NATuG 3.0 or the Action Repetition button.
2) If they quit without saving anything, they should be prompted to save. 
3) Things that need saving: Nucleic Acid info, Domain stuff including angles and counts subpanels, Junctions, Nicks, Links, and Sequences. Perhaps we should give them an option to save snapshots?

Note that the current warning when they change domain information is that they are losing junction information, but there is much more they are losing in the current version. See (3) above.

**Comment by 404Wolf** [comment]
@DNAcer 
This is already a feature; you can save everything as a package at once with file > save (control + s). I can add a button next to the NATuG3 label too if you'd like.

I just did a slight refactor on the saving system to automatically dump and load program states on close and open as opposed to having eclectic "restored.csv" save files in multiple locations. When you exit now, a restored.natug package is placed in the saves folder, and is automatically reloaded when you reload.

Also, snapshots are in fact all just program saves. They are located in saves/snapshots, and the names match up with what they are named in the snapshots tab.

**Comment by DNAcer** [comment]
I know there is a save option in the menu, but when there is a save button visible on the screen, people are unlikely to hunt around in the menu for saving. Many will not realized that they are not saving everything. That's why we really need a prominent button marked Save All.

**Comment by 404Wolf** [comment]
Ah, that makes sense. It seems a bit redundant given that the current state is _always_ saved in a snapshot upon every change, but this wasn't hard to add so I implemented the button next to the program label in the toolbar.
