### ISSUE TITLE
Warnig when deleting snapshots.

### ISSUE THREAD

**Issue by DNAcer** [NATuG3/NATuG3#57]
As it stands you can delete tons of snapshots with one misclicked button. It would be nice to have the user confirm before deleting so much.

**Comment by 404Wolf** [comment]
![image](https://github.com/NATuG3/NATuG3/assets/108041238/7643263c-3ba2-43bd-85c2-9049fc5bbfc9)
![image](https://github.com/NATuG3/NATuG3/assets/108041238/e45d7d10-8c66-4d6c-8383-52b4cf88c09a)
