### ISSUE TITLE
Nicking Not Working

### ISSUE THREAD

**Issue by DNAcer** [NATuG3/NATuG3#7]
For some reason, when I try to put a nick on a tube, the whole strand graph disappears until I update graphs manually.
<img width="1440" alt="Screen Shot 2022-11-24 at 12 33 04 AM" src="https://user-images.githubusercontent.com/118033291/203702828-18cc04a8-b8b9-49a1-85a4-5a5a6604c077.png">

**Comment by 404Wolf** [comment]
This is a known issue. I've changed the backend in such a way as to make nicking not work, since I want to rework nicking to actually break apart strands. I'm going to prioritize sequencing and then return to this. For now I've disabled the nicker mode to prevent getting this error.

**Comment by 404Wolf** [comment]
Nicking works again!
